# Generated by Django 5.2.17 on 2026-08-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("title_ru", models.CharField(max_length=200, null=True)),
                ("title_en", models.CharField(max_length=200, null=True)),
                ("content", models.TextField()),
                ("content_ru", models.TextField(null=True)),
                ("content_en", models.TextField(null=True)),
                ("link_url", models.URLField(blank=True)),
                ("link_text", models.CharField(blank=True, max_length=100)),
                (
                    "link_text_ru",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "link_text_en",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Объявление",
                "verbose_name_plural": "Объявления",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClergyMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Сан / должность"),
                ),
                (
                    "title_ru",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Сан / должность"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Сан / должность"
                    ),
                ),
                ("bio", models.TextField(blank=True)),
                ("bio_ru", models.TextField(blank=True, null=True)),
                ("bio_en", models.TextField(blank=True, null=True)),
                ("photo", models.ImageField(blank=True, upload_to="clergy/")),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Клирик",
                "verbose_name_plural": "Духовенство",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("message", models.TextField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения с сайта",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parish_name",
                    models.CharField(
                        default="Приход Благовещения Пресвятой Богородицы",
                        max_length=200,
                    ),
                ),
                (
                    "parish_name_ru",
                    models.CharField(
                        default="Приход Благовещения Пресвятой Богородицы",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "parish_name_en",
                    models.CharField(
                        default="Приход Благовещения Пресвятой Богородицы",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "city",
                    models.CharField(default="Джексонвиль, Флорида", max_length=120),
                ),
                (
                    "city_ru",
                    models.CharField(
                        default="Джексонвиль, Флорида", max_length=120, null=True
                    ),
                ),
                (
                    "city_en",
                    models.CharField(
                        default="Джексонвиль, Флорида", max_length=120, null=True
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=255)),
                ("address_ru", models.CharField(blank=True, max_length=255, null=True)),
                ("address_en", models.CharField(blank=True, max_length=255, null=True)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "realm_giving_url",
                    models.URLField(
                        blank=True,
                        help_text="Кнопка «Пожертвовать» ведёт сюда.",
                        verbose_name="Ссылка на пожертвования (Realm)",
                    ),
                ),
                (
                    "realm_membership_url",
                    models.URLField(
                        blank=True,
                        help_text="Кнопка «Стать членом прихода» ведёт сюда.",
                        verbose_name="Ссылка на членство (Realm)",
                    ),
                ),
                (
                    "realm_embed_code",
                    models.TextField(
                        blank=True,
                        help_text="Необязательно: вставить iframe/виджет онлайн-пожертвований, если Realm его даёт.",
                        verbose_name="HTML-код виджета Realm",
                    ),
                ),
                ("facebook_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("youtube_url", models.URLField(blank=True)),
            ],
            options={
                "verbose_name": "Настройки сайта",
                "verbose_name_plural": "Настройки сайта",
            },
        ),
        migrations.CreateModel(
            name="PageText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page", models.SlugField(max_length=100)),
                ("block", models.SlugField(max_length=100)),
                ("label", models.CharField(blank=True, max_length=200)),
                ("body", models.TextField(blank=True)),
                ("body_ru", models.TextField(blank=True, null=True)),
                ("body_en", models.TextField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Редактируемый блок",
                "verbose_name_plural": "Редактируемые блоки",
                "unique_together": {("page", "block")},
            },
        ),
    ]
