# Generated by Django 5.2.17 on 2026-08-11 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="hero_image",
            field=models.ImageField(
                blank=True, upload_to="hero/", verbose_name="Фото на главной"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_lede",
            field=models.CharField(
                blank=True,
                help_text="Одна-две строки под названием прихода на первом экране.",
                max_length=300,
                verbose_name="Подпись на главной",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_lede_en",
            field=models.CharField(
                blank=True,
                help_text="Одна-две строки под названием прихода на первом экране.",
                max_length=300,
                null=True,
                verbose_name="Подпись на главной",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_lede_ru",
            field=models.CharField(
                blank=True,
                help_text="Одна-две строки под названием прихода на первом экране.",
                max_length=300,
                null=True,
                verbose_name="Подпись на главной",
            ),
        ),
    ]
