# Generated by Django 5.2.17 on 2026-08-11 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_sitesettings_hero_image_sitesettings_hero_lede_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DonationPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "intro",
                    models.TextField(
                        blank=True,
                        help_text="Коротко: на что идут пожертвования.",
                        verbose_name="Вступление",
                    ),
                ),
                (
                    "intro_ru",
                    models.TextField(
                        blank=True,
                        help_text="Коротко: на что идут пожертвования.",
                        null=True,
                        verbose_name="Вступление",
                    ),
                ),
                (
                    "intro_en",
                    models.TextField(
                        blank=True,
                        help_text="Коротко: на что идут пожертвования.",
                        null=True,
                        verbose_name="Вступление",
                    ),
                ),
            ],
            options={
                "verbose_name": "Страница пожертвований",
                "verbose_name_plural": "Страница пожертвований",
            },
        ),
        migrations.CreateModel(
            name="FirstVisitPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "intro",
                    models.TextField(
                        blank=True,
                        help_text="Первые два-три абзаца: кто мы и почему вам здесь рады.",
                        verbose_name="Приветствие",
                    ),
                ),
                (
                    "intro_ru",
                    models.TextField(
                        blank=True,
                        help_text="Первые два-три абзаца: кто мы и почему вам здесь рады.",
                        null=True,
                        verbose_name="Приветствие",
                    ),
                ),
                (
                    "intro_en",
                    models.TextField(
                        blank=True,
                        help_text="Первые два-три абзаца: кто мы и почему вам здесь рады.",
                        null=True,
                        verbose_name="Приветствие",
                    ),
                ),
                (
                    "when_text",
                    models.CharField(
                        blank=True,
                        help_text="Например «Часы и Литургия — в 9:30 утра по воскресеньям».",
                        max_length=300,
                        verbose_name="Когда приходить",
                    ),
                ),
                (
                    "when_text_ru",
                    models.CharField(
                        blank=True,
                        help_text="Например «Часы и Литургия — в 9:30 утра по воскресеньям».",
                        max_length=300,
                        null=True,
                        verbose_name="Когда приходить",
                    ),
                ),
                (
                    "when_text_en",
                    models.CharField(
                        blank=True,
                        help_text="Например «Часы и Литургия — в 9:30 утра по воскресеньям».",
                        max_length=300,
                        null=True,
                        verbose_name="Когда приходить",
                    ),
                ),
                (
                    "what_to_expect",
                    models.TextField(
                        blank=True,
                        help_text="Сколько идёт, на каком языке, что бывает после.",
                        verbose_name="Как проходит служба",
                    ),
                ),
                (
                    "what_to_expect_ru",
                    models.TextField(
                        blank=True,
                        help_text="Сколько идёт, на каком языке, что бывает после.",
                        null=True,
                        verbose_name="Как проходит служба",
                    ),
                ),
                (
                    "what_to_expect_en",
                    models.TextField(
                        blank=True,
                        help_text="Сколько идёт, на каком языке, что бывает после.",
                        null=True,
                        verbose_name="Как проходит служба",
                    ),
                ),
                (
                    "practical",
                    models.TextField(
                        blank=True,
                        help_text="Парковка, как одеться, к кому подойти с вопросом.",
                        verbose_name="Практическое",
                    ),
                ),
                (
                    "practical_ru",
                    models.TextField(
                        blank=True,
                        help_text="Парковка, как одеться, к кому подойти с вопросом.",
                        null=True,
                        verbose_name="Практическое",
                    ),
                ),
                (
                    "practical_en",
                    models.TextField(
                        blank=True,
                        help_text="Парковка, как одеться, к кому подойти с вопросом.",
                        null=True,
                        verbose_name="Практическое",
                    ),
                ),
                (
                    "communion_note",
                    models.TextField(
                        blank=True,
                        help_text="Кто может причащаться и что сделать заранее.",
                        verbose_name="О причастии",
                    ),
                ),
                (
                    "communion_note_ru",
                    models.TextField(
                        blank=True,
                        help_text="Кто может причащаться и что сделать заранее.",
                        null=True,
                        verbose_name="О причастии",
                    ),
                ),
                (
                    "communion_note_en",
                    models.TextField(
                        blank=True,
                        help_text="Кто может причащаться и что сделать заранее.",
                        null=True,
                        verbose_name="О причастии",
                    ),
                ),
            ],
            options={
                "verbose_name": "Страница «Впервые здесь?»",
                "verbose_name_plural": "Страница «Впервые здесь?»",
            },
        ),
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Имя")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-mail"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=50, verbose_name="Телефон"),
                ),
                (
                    "about",
                    models.CharField(
                        choices=[
                            ("orthodox", "Я православный христианин"),
                            ("curious", "Я не православный, но хочу узнать больше"),
                            ("priest", "Хочу поговорить со священником"),
                        ],
                        max_length=20,
                        verbose_name="О себе",
                    ),
                ),
                (
                    "preferred_contact",
                    models.CharField(
                        choices=[
                            ("email", "Электронная почта"),
                            ("phone", "Телефон"),
                            ("either", "Всё равно"),
                        ],
                        default="either",
                        max_length=20,
                        verbose_name="Как удобнее связаться",
                    ),
                ),
                (
                    "best_time",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Удобное время"
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="Сообщение")),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_handled",
                    models.BooleanField(default=False, verbose_name="Отвечено"),
                ),
            ],
            options={
                "verbose_name": "Обращение новичка",
                "verbose_name_plural": "Обращения новичков",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="DonationMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="Название")),
                (
                    "title_ru",
                    models.CharField(
                        max_length=120, null=True, verbose_name="Название"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=120, null=True, verbose_name="Название"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Пояснение")),
                (
                    "description_ru",
                    models.TextField(blank=True, null=True, verbose_name="Пояснение"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, null=True, verbose_name="Пояснение"),
                ),
                ("url", models.URLField(blank=True, verbose_name="Ссылка")),
                (
                    "button_label",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Надпись на кнопке"
                    ),
                ),
                (
                    "button_label_ru",
                    models.CharField(
                        blank=True,
                        max_length=60,
                        null=True,
                        verbose_name="Надпись на кнопке",
                    ),
                ),
                (
                    "button_label_en",
                    models.CharField(
                        blank=True,
                        max_length=60,
                        null=True,
                        verbose_name="Надпись на кнопке",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="methods",
                        to="core.donationpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Способ пожертвования",
                "verbose_name_plural": "Способы пожертвования",
                "ordering": ["order"],
            },
        ),
    ]
