# Generated by Django 5.2.17 on 2026-08-12 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_donationpage_firstvisitpage_inquiry_donationmethod"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="parish_name_short",
            field=models.CharField(
                default="Благовещение",
                help_text="Для тесных мест: шапка портала, вкладка браузера.",
                max_length=60,
                verbose_name="Короткое название",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="parish_name_short_en",
            field=models.CharField(
                default="Благовещение",
                help_text="Для тесных мест: шапка портала, вкладка браузера.",
                max_length=60,
                null=True,
                verbose_name="Короткое название",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="parish_name_short_ru",
            field=models.CharField(
                default="Благовещение",
                help_text="Для тесных мест: шапка портала, вкладка браузера.",
                max_length=60,
                null=True,
                verbose_name="Короткое название",
            ),
        ),
    ]
