# Generated by Django 5.2.17 on 2026-08-13 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_sitesettings_parish_name_short_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="founded_year",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Показывается в полосе под первым экраном. Пусто — клетки не будет.",
                null=True,
                verbose_name="Год основания",
            ),
        ),
    ]
