# Generated by Django 5.2.17 on 2026-08-11 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RussianSchoolPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("description_ru", models.TextField(blank=True, null=True)),
                ("description_en", models.TextField(blank=True, null=True)),
                ("cover_image", models.ImageField(blank=True, upload_to="school/")),
                ("age_from", models.PositiveIntegerField(default=5)),
                (
                    "schedule_text",
                    models.CharField(
                        blank=True,
                        help_text="Например «По понедельникам, 16:00–20:00»",
                        max_length=300,
                    ),
                ),
                (
                    "schedule_text_ru",
                    models.CharField(
                        blank=True,
                        help_text="Например «По понедельникам, 16:00–20:00»",
                        max_length=300,
                        null=True,
                    ),
                ),
                (
                    "schedule_text_en",
                    models.CharField(
                        blank=True,
                        help_text="Например «По понедельникам, 16:00–20:00»",
                        max_length=300,
                        null=True,
                    ),
                ),
                ("term_start", models.DateField(blank=True, null=True)),
                ("term_end", models.DateField(blank=True, null=True)),
                ("tuition_note", models.CharField(blank=True, max_length=300)),
                (
                    "tuition_note_ru",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "tuition_note_en",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("enrollment_open", models.BooleanField(default=True)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "verbose_name": "Русская школа",
                "verbose_name_plural": "Русская школа",
            },
        ),
        migrations.CreateModel(
            name="RussianSchoolPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="school/photos/")),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="school.russianschoolpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото школы",
                "verbose_name_plural": "Фото школы",
                "ordering": ["order"],
            },
        ),
    ]
