# Generated by Django 5.2.17 on 2026-08-11 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RecurringServiceRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Для себя, в списке правил — например «Воскресное»",
                        max_length=200,
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Понедельник"),
                            (1, "Вторник"),
                            (2, "Среда"),
                            (3, "Четверг"),
                            (4, "Пятница"),
                            (5, "Суббота"),
                            (6, "Воскресенье"),
                        ]
                    ),
                ),
                (
                    "default_fasting_level",
                    models.CharField(
                        choices=[
                            ("none", "Обычный день"),
                            ("fast", "Пост"),
                            ("fish_wine_oil", "Разрешается рыба, вино и елей"),
                            ("wine_oil", "Разрешается вино и елей"),
                            ("strict", "Строгий пост (сухоядение)"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Регулярное правило расписания",
                "verbose_name_plural": "Регулярные правила расписания",
                "ordering": ["weekday"],
            },
        ),
        migrations.CreateModel(
            name="ServiceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("name_ru", models.CharField(max_length=100, null=True)),
                ("name_en", models.CharField(max_length=100, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Тип службы",
                "verbose_name_plural": "Типы служб",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ServiceDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "feast_title",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Праздник/память"
                    ),
                ),
                (
                    "feast_title_ru",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Праздник/память",
                    ),
                ),
                (
                    "feast_title_en",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Праздник/память",
                    ),
                ),
                (
                    "fasting_level",
                    models.CharField(
                        choices=[
                            ("none", "Обычный день"),
                            ("fast", "Пост"),
                            ("fish_wine_oil", "Разрешается рыба, вино и елей"),
                            ("wine_oil", "Разрешается вино и елей"),
                            ("strict", "Строгий пост (сухоядение)"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("note_ru", models.TextField(blank=True, null=True)),
                ("note_en", models.TextField(blank=True, null=True)),
                ("is_published", models.BooleanField(default=True)),
                (
                    "generated_from_rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_days",
                        to="services.recurringservicerule",
                    ),
                ),
            ],
            options={
                "verbose_name": "День службы",
                "verbose_name_plural": "Расписание богослужений",
                "ordering": ["date"],
                "unique_together": {("date",)},
            },
        ),
        migrations.CreateModel(
            name="ServiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.TimeField()),
                ("note", models.CharField(blank=True, max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="services.serviceday",
                    ),
                ),
                (
                    "service_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="services.servicetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Служба",
                "verbose_name_plural": "Службы",
                "ordering": ["order", "time"],
            },
        ),
        migrations.CreateModel(
            name="RecurringServiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.TimeField()),
                ("note", models.CharField(blank=True, max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="services.recurringservicerule",
                    ),
                ),
                (
                    "service_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="services.servicetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Служба в правиле",
                "verbose_name_plural": "Службы в правиле",
                "ordering": ["order", "time"],
            },
        ),
    ]
