# Generated by Django 5.2.17 on 2026-08-11 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceday",
            name="is_major",
            field=models.BooleanField(
                default=False,
                help_text="Двунадесятый или престольный праздник — название выделяется на карточке.",
                verbose_name="Великий праздник",
            ),
        ),
        migrations.AlterField(
            model_name="recurringservicerule",
            name="default_fasting_level",
            field=models.CharField(
                choices=[
                    ("none", "Обычный день"),
                    ("fast", "Пост"),
                    ("fish_wine_oil", "Рыба, вино и елей"),
                    ("wine_oil", "Вино и елей"),
                    ("dry", "Сухоядение"),
                    ("strict", "Строгий пост"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="serviceday",
            name="fasting_level",
            field=models.CharField(
                choices=[
                    ("none", "Обычный день"),
                    ("fast", "Пост"),
                    ("fish_wine_oil", "Рыба, вино и елей"),
                    ("wine_oil", "Вино и елей"),
                    ("dry", "Сухоядение"),
                    ("strict", "Строгий пост"),
                ],
                default="none",
                max_length=20,
            ),
        ),
    ]
