# Generated by Django 5.2.17 on 2026-08-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ministries", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ministry",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, blank=True, max_length=220, unique=True
            ),
        ),
    ]
