# Generated by Django 5.2.17 on 2026-08-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HistoryMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=200)),
                ("title_ru", models.CharField(max_length=200, null=True)),
                ("title_en", models.CharField(max_length=200, null=True)),
                ("description", models.TextField(blank=True)),
                ("description_ru", models.TextField(blank=True, null=True)),
                ("description_en", models.TextField(blank=True, null=True)),
                ("image", models.ImageField(blank=True, upload_to="history/")),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Веха истории",
                "verbose_name_plural": "История прихода",
                "ordering": ["order", "year"],
            },
        ),
    ]
