# Generated by Django 5.2.17 on 2026-08-11 22:35

import django.core.files.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ministries", "0002_alter_ministry_slug"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Название")),
                ("date", models.DateField(verbose_name="Дата")),
                ("time", models.TimeField(blank=True, null=True, verbose_name="Время")),
                (
                    "location",
                    models.CharField(blank=True, max_length=300, verbose_name="Место"),
                ),
                ("agenda", models.TextField(blank=True, verbose_name="Повестка")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Запланировано"),
                            ("held", "Состоялось"),
                            ("cancelled", "Отменено"),
                        ],
                        default="planned",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Заседание совета",
                "verbose_name_plural": "Заседания совета",
                "ordering": ["-date", "-time"],
            },
        ),
        migrations.CreateModel(
            name="CouncilProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("idea", "Идея"),
                            ("planned", "Запланирован"),
                            ("in_progress", "В работе"),
                            ("done", "Завершён"),
                        ],
                        default="planned",
                        max_length=12,
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="Срок"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="council_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Проект совета",
                "verbose_name_plural": "Проекты совета",
                "ordering": ["status", "due_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GroupMailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("council", "Совет прихода"),
                            ("parishioners", "Все одобренные прихожане"),
                            ("ministry", "Одно служение"),
                        ],
                        max_length=14,
                        verbose_name="Кому",
                    ),
                ),
                ("subject", models.CharField(max_length=300, verbose_name="Тема")),
                ("body", models.TextField(verbose_name="Текст")),
                (
                    "recipient_count",
                    models.PositiveIntegerField(default=0, verbose_name="Получателей"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ministry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mailings",
                        to="ministries.ministry",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_mailings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GroupMailingAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        storage=django.core.files.storage.FileSystemStorage(
                            location="/home/user/annunciation/private_media"
                        ),
                        upload_to="council/mailings/%Y/%m/",
                    ),
                ),
                ("original_name", models.CharField(blank=True, max_length=300)),
                (
                    "mailing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="council.groupmailing",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вложение рассылки",
                "verbose_name_plural": "Вложения рассылок",
            },
        ),
        migrations.CreateModel(
            name="MeetingDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Название")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("financial", "Финансовый отчёт"),
                            ("committee", "Отчёт комиссии"),
                            ("audio", "Аудиозапись"),
                            ("photo", "Фото"),
                            ("presentation", "Презентация"),
                            ("other", "Другой документ"),
                        ],
                        default="other",
                        max_length=12,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        storage=django.core.files.storage.FileSystemStorage(
                            location="/home/user/annunciation/private_media"
                        ),
                        upload_to="council/meeting_docs/%Y/%m/",
                        verbose_name="Файл",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "council_only",
                    models.BooleanField(
                        default=True,
                        help_text="Выключите, чтобы файл увидели все одобренные прихожане.",
                        verbose_name="Только для совета",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Опубликован"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="council.meeting",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_meeting_docs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Документ заседания",
                "verbose_name_plural": "Документы заседаний",
                "ordering": ["category", "title"],
            },
        ),
        migrations.CreateModel(
            name="MembershipRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=30, verbose_name="Телефон"),
                ),
                (
                    "parish_connection",
                    models.CharField(
                        blank=True,
                        help_text="Как человек связан с приходом — необязательно.",
                        max_length=200,
                        verbose_name="Связь с приходом",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="Что заявитель хочет сообщить совету.",
                        verbose_name="Сообщение",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "На рассмотрении"),
                            ("approved", "Одобрено"),
                            ("rejected", "Отклонено"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "is_council_member",
                    models.BooleanField(
                        default=False,
                        help_text="Отметьте до одобрения, чтобы дать полный доступ — протоколы для совета и финансовые отчёты.",
                        verbose_name="Член совета",
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_membership_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membership_request",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на доступ",
                "verbose_name_plural": "Заявки на доступ",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Protocol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Название")),
                ("body", models.TextField(blank=True, verbose_name="Протокол")),
                (
                    "decisions",
                    models.TextField(
                        blank=True,
                        help_text="Что решили, кто отвечает, к какому сроку.",
                        verbose_name="Решения",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Необязательно: приложенный документ (PDF / DOCX).",
                        null=True,
                        storage=django.core.files.storage.FileSystemStorage(
                            location="/home/user/annunciation/private_media"
                        ),
                        upload_to="council/protocols/",
                        verbose_name="Файл",
                    ),
                ),
                (
                    "council_only",
                    models.BooleanField(
                        default=True,
                        help_text="Выключите, чтобы протокол увидели все одобренные прихожане.",
                        verbose_name="Только для совета",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Черновики в портале не видны.",
                        verbose_name="Опубликован",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_protocols",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="protocols",
                        to="council.meeting",
                    ),
                ),
            ],
            options={
                "verbose_name": "Протокол",
                "verbose_name_plural": "Протоколы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ActionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Задача")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="Срок"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "В работе"), ("done", "Выполнено")],
                        default="open",
                        max_length=8,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="action_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ministry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="action_items",
                        to="ministries.ministry",
                    ),
                ),
                (
                    "ministry_project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="action_items",
                        to="ministries.ministryproject",
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="action_items",
                        to="council.meeting",
                    ),
                ),
                (
                    "protocol",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="action_items",
                        to="council.protocol",
                    ),
                ),
            ],
            options={
                "verbose_name": "Поручение",
                "verbose_name_plural": "Поручения",
                "ordering": ["status", "due_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Название")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("financial", "Финансовый"),
                            ("activity", "О деятельности"),
                            ("other", "Другое"),
                        ],
                        default="financial",
                        max_length=12,
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        blank=True,
                        help_text="Например «I квартал 2026» или «2025 год».",
                        max_length=100,
                        verbose_name="Период",
                    ),
                ),
                ("body", models.TextField(blank=True, verbose_name="Кратко")),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Приложенный отчёт (PDF / XLSX) — доступен одобренным участникам.",
                        null=True,
                        storage=django.core.files.storage.FileSystemStorage(
                            location="/home/user/annunciation/private_media"
                        ),
                        upload_to="council/reports/",
                        verbose_name="Файл",
                    ),
                ),
                (
                    "council_only",
                    models.BooleanField(
                        default=True,
                        help_text="Выключите, чтобы отчёт увидели все одобренные прихожане.",
                        verbose_name="Только для совета",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Опубликован"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_council_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Отчёт совета",
                "verbose_name_plural": "Отчёты совета",
                "ordering": ["-created_at"],
            },
        ),
    ]
