# Generated by Django 5.2.17 on 2026-08-11 22:52

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("council", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupmailingattachment",
            name="file",
            field=models.FileField(
                storage=core.storage.PrivateMediaStorage(),
                upload_to="council/mailings/%Y/%m/",
            ),
        ),
        migrations.AlterField(
            model_name="meetingdocument",
            name="file",
            field=models.FileField(
                storage=core.storage.PrivateMediaStorage(),
                upload_to="council/meeting_docs/%Y/%m/",
                verbose_name="Файл",
            ),
        ),
        migrations.AlterField(
            model_name="protocol",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Необязательно: приложенный документ (PDF / DOCX).",
                null=True,
                storage=core.storage.PrivateMediaStorage(),
                upload_to="council/protocols/",
                verbose_name="Файл",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Приложенный отчёт (PDF / XLSX) — доступен одобренным участникам.",
                null=True,
                storage=core.storage.PrivateMediaStorage(),
                upload_to="council/reports/",
                verbose_name="Файл",
            ),
        ),
    ]
