# Generated by Django 5.2.17 on 2026-08-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("calendar", "Календарь"), ("bulletin", "Бюллетень")],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("title_ru", models.CharField(max_length=200, null=True)),
                ("title_en", models.CharField(max_length=200, null=True)),
                (
                    "period_label",
                    models.CharField(
                        help_text="Например «Август 2026» или «Неделя 17–23 августа»",
                        max_length=100,
                        verbose_name="Период",
                    ),
                ),
                (
                    "period_label_ru",
                    models.CharField(
                        help_text="Например «Август 2026» или «Неделя 17–23 августа»",
                        max_length=100,
                        null=True,
                        verbose_name="Период",
                    ),
                ),
                (
                    "period_label_en",
                    models.CharField(
                        help_text="Например «Август 2026» или «Неделя 17–23 августа»",
                        max_length=100,
                        null=True,
                        verbose_name="Период",
                    ),
                ),
                ("pdf_file", models.FileField(upload_to="publications/%Y/")),
                ("published_at", models.DateField()),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Публикация",
                "verbose_name_plural": "Календарь и бюллетень",
                "ordering": ["-published_at"],
            },
        ),
    ]
