# Generated by Django 5.2.17 on 2026-08-11 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BuildingProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Строительство нового храма", max_length=200
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        default="Строительство нового храма", max_length=200, null=True
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        default="Строительство нового храма", max_length=200, null=True
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("description_ru", models.TextField(blank=True, null=True)),
                ("description_en", models.TextField(blank=True, null=True)),
                ("cover_image", models.ImageField(blank=True, upload_to="building/")),
                (
                    "goal_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "raised_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Обновляется вручную по данным Realm/казначея — прямой синхронизации нет.",
                        max_digits=10,
                    ),
                ),
                ("raised_updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Строительный проект",
                "verbose_name_plural": "Строительный проект",
            },
        ),
        migrations.CreateModel(
            name="BuildingProjectPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="building/photos/")),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="building.buildingproject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото стройки",
                "verbose_name_plural": "Фото стройки",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="BuildingProjectUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("title", models.CharField(max_length=200)),
                ("title_ru", models.CharField(max_length=200, null=True)),
                ("title_en", models.CharField(max_length=200, null=True)),
                ("body", models.TextField(blank=True)),
                ("body_ru", models.TextField(blank=True, null=True)),
                ("body_en", models.TextField(blank=True, null=True)),
                (
                    "cover_image",
                    models.ImageField(blank=True, upload_to="building/updates/"),
                ),
                ("is_published", models.BooleanField(default=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates",
                        to="building.buildingproject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Новость стройки",
                "verbose_name_plural": "Новости стройки",
                "ordering": ["-date"],
            },
        ),
    ]
