# Generated by Django 5.2.17 on 2026-08-11 22:52

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CommemorationBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Название"
                    ),
                ),
                (
                    "service_date",
                    models.DateField(blank=True, null=True, verbose_name="К службе"),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        storage=core.storage.PrivateMediaStorage(),
                        upload_to="commemorations/batches/",
                        verbose_name="PDF",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Собрана"),
                            ("pdf_ready", "PDF готов"),
                            ("printed", "Напечатана"),
                            ("failed", "Ошибка"),
                        ],
                        default="created",
                        max_length=20,
                        verbose_name="Состояние",
                    ),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="Ошибка")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Собрана"),
                ),
                (
                    "printed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Напечатана"
                    ),
                ),
            ],
            options={
                "verbose_name": "пачка записок",
                "verbose_name_plural": "пачки записок",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Commemoration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("liturgy", "Обедня — на ближайшей литургии"),
                            ("sorokoust", "Сорокоуст — 40 литургий"),
                        ],
                        default="liturgy",
                        max_length=20,
                        verbose_name="Вид поминовения",
                    ),
                ),
                (
                    "requester_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Кто подаёт"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-mail"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=30, verbose_name="Телефон"),
                ),
                (
                    "living_names",
                    models.TextField(blank=True, verbose_name="О здравии"),
                ),
                (
                    "departed_names",
                    models.TextField(blank=True, verbose_name="О упокоении"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, verbose_name="Примечание для священника"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ждёт литургии"),
                            ("batched", "В пачке"),
                            ("completed", "Вычитана"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Состояние",
                    ),
                ),
                (
                    "first_service_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Первая литургия"
                    ),
                ),
                (
                    "total_liturgies",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Всего литургий"
                    ),
                ),
                (
                    "printed_count",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Напечатано раз"
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Подана"),
                ),
                (
                    "batched_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Взята в пачку"
                    ),
                ),
                (
                    "printed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Напечатана"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Вычитана"
                    ),
                ),
                (
                    "batches",
                    models.ManyToManyField(
                        blank=True,
                        related_name="notes",
                        to="commemorations.commemorationbatch",
                        verbose_name="Пачки",
                    ),
                ),
            ],
            options={
                "verbose_name": "записка",
                "verbose_name_plural": "записки",
                "ordering": ["-submitted_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "kind"], name="commemorati_status_4e6783_idx"
                    )
                ],
            },
        ),
    ]
